version: '3.5'

services:
  mypostgres:
    container_name: postgres_container
    image: postgres:10.15-alpine
    env_file: 
      - ./TopicExtractor/.envs/.local/.mypostgres
    volumes: 
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_bkup_data:/backups
    ports: 
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

  mypgadmin4:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file: 
      - ./TopicExtractor/.envs/.local/.mypgadmin4
    volumes:
       - pgadmin:/root/.pgadmin
    ports: 
      - '80:80'
    networks:
      - postgres
    restart: unless-stopped
  
networks:
  postgres:
    driver: bridge

volumes: 
  local_postgres_data:
  local_postgres_bkup_data:
  pgadmin:
